---
- name: Change User Shell to zsh
  become: yes
  user:
    name: "{{ default_user }}"
    shell: /bin/zsh

- name: Configure Git - Default Branch
  become: yes
  become_user: "{{ default_user }}"
  ansible.builtin.command: git config --global init.defaultBranch "main"

- name: Configure Git - Display Name
  become: yes
  become_user: "{{ default_user }}"
  ansible.builtin.command: git config --global user.name '{{default_user_name}}'

- name: Configure Git - Email
  become: yes
  become_user: "{{ default_user }}"
  ansible.builtin.command: git config --global user.email {{default_user_email}}



